name: Publish @celine/bibhtml to NPM

on:
  push:
    tags:
      - 'bibhtml/v*'
    paths:
      - 'bibhtml/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g. patch, minor, major, or specific version)'
        required: true
        default: 'patch'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bibhtml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
      
      - name: Build package
        run: bun run build:all
      
      - name: Set up npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Version and publish (tag-based)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed 's/bibhtml\/v//')
          npm version $VERSION --no-git-tag-version
          npm publish --access public
      
      - name: Version and publish (manual)
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          npm publish --access public